spring:
  profiles:
    active: prod
  application:
    name: spring-boot-minio
  servlet:
    multipart:
      max-file-size: -1
server:
  port: 9000
minio:
  # 访问的url
  endpoint: http://192.168.52.100
  # API的端口
  port: 9001
  # 秘钥
  accessKey: JX0LEFPHRQ9XXKR06LTY
  secretKey: V1+3ccKhDaiEsZotzEV9YlZ2pibuJ4n9c6HTaL9L
  secure: false
  bucket-name: test # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小